### ISSUE TITLE
@JsonClass annotation is not generated

### ISSUE THREAD

**Issue by Andre777** [Yelp/swagger-gradle-codegen#117]
**First of all thank you very much for the plugin!** 

About issue, created dummy project to try: [https://github.com/Andre777/test_swagger](url) and noticed that `@JsonClass(generateAdapter)` annotation is not generated in the models.
Please, could you look what I'm doing wrong.

**Comment by cortinico** [comment]
Hi @Andre777 

That is expected as the `@JsonClass(generateAdapter)` annotation is currently on master but unreleased. Will be available in the upcoming version (1.4.0) that will be released in the next days.

**Comment by macisamuele** [comment]
The [new version](https://github.com/Yelp/swagger-gradle-codegen/releases/tag/1.4.0) has been release, hence closing this.

Feel free to re-open this if you are still experiencing the same problem.
