### ISSUE TITLE
How to remove usingPUT?

### ISSUE THREAD

**Issue by klaszlo8207** [Yelp/swagger-gradle-codegen#146]
1, How to remove ALL usingPUT/usingPOST/UsingGET1/using* at the end of the suspend fun?

2, How to remove header:

"X-Operation-ID: blabla"?

3, How to generate responses under models/responses and requests under models/requests?

BTW, Thanks for the library!

**Comment by klaszlo8207** [comment]
2, is solved

**Comment by klaszlo8207** [comment]
1, solved sorry it was in the spec file: "operationId"

I just simple removed that chars

**Comment by klaszlo8207** [comment]
3, What is the class that can I refactor/update to create that two responses/requests directories? 

I think this is possible, because we know what is the Request classes and what is the Response classes, so in this way we can seperate it...

**Comment by cortinico** [comment]
> 3, What is the class that can I refactor/update to create that two responses/requests directories?

It's the KotlinGenerator class https://github.com/Yelp/swagger-gradle-codegen/blob/master/gradle-plugin/plugin/src/main/java/com/yelp/codegen/KotlinGenerator.kt

**Comment by klaszlo8207** [comment]
Thanks, I will try it

**Comment by cortinico** [comment]
I'll close this issue as it's a mixture of questions. Should you need further support on point 3, please open another issue 👌
