### ISSUE TITLE
Support using java.time instead of ThreeTenBp in generated code

### ISSUE THREAD

**Issue by doug-precocity** [Yelp/swagger-gradle-codegen#150]
In Android, using core library [desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring) is now favored over the use of [ThreeTenBp](https://github.com/ThreeTen/threetenbp) to make java.time classes available in the project.  However, swagger-gradle-codegen generates codes that imports from `org.threeten.bp`.  It would be great if we could configure swagger-gradle-codegen to use java.time instead

**Comment by cortinico** [comment]
I've just realized that we already support this. It has been merged in #138.
It's available on `master` or on the upcoming version of the plugin
