### ISSUE TITLE
Read Swagger.json from URL 

### ISSUE THREAD

**Issue by yudhir** [Yelp/swagger-gradle-codegen#27]
Can Specification be read from a URL ?

Also Do you have any sample code of using these with Rx and Retrofit?

**Comment by cortinico** [comment]
> Can Specification be read from a URL ?

Currently not. The fastest way to achieve this is to have a gradle task that will download your spec file in a specific location that you can then use for the `inputFile` configuration. Have a look at https://github.com/michel-kraemer/gradle-download-task

> Also Do you have any sample code of using these with Rx and Retrofit?

Have you seen the `generated-code` sample here?
https://github.com/Yelp/swagger-gradle-codegen/tree/master/samples/generated-code
Or are you looking for a different example?

**Comment by yudhir** [comment]
Great. 

Yea, I want to see how retrofit is instantiated with the type converters.  Better yet Authentication implementations.

**Comment by cortinico** [comment]
You can have a look at #28

**Comment by yudhir** [comment]
Thanks !
