### ISSUE TITLE
Build failed on Version 1.1.0

### ISSUE THREAD

**Issue by chathudan** [Yelp/swagger-gradle-codegen#38]
Once I update the version to **1.1.0** it gave build failure  but the plugin is working with version **1.0.0** 

```
> Task :generateSwagger FAILED
####################
Yelp Swagger Codegen
####################
Platform         kotlin
Package          com.yelp.codegen.integrations
specName         integration
specVers         1.0.0
input            /Users/chatura/swagger-gen/swagger-gradle-codegen-master/samples/sample_specs.json
output           /Users/chatura/swagger-gen/swagger-gradle-codegen-master/samples/groovy-android/src/main/java
groupId          com.yelp.codegen.integrations
artifactId       com.yelp.codegen.integrations
features         Accept-Language

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateSwagger'.
> com/yelp/codegen/utils/InlineModelResolver has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

These are my configurations 

```
------------------------------------------------------------
Gradle 5.5
------------------------------------------------------------

Build time:   2019-06-28 17:36:05 UTC
Revision:     83820928f3ada1a3a1dbd9a6c0d47eb3f199378f

Kotlin:       1.3.31
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          1.8.0_212 (AdoptOpenJDK 25.212-b04)
OS:           Mac OS X 10.13.6 x86_64
```

**Comment by cortinico** [comment]
Thanks for reporting it @chathudan 
I'm verifying and will eventually publish a `1.1.1` with this a fix (looks like the `1.1.0` was compiled with Java11 rather than 8).

**Comment by chathudan** [comment]
Thank you, waiting for the release.

**Comment by cortinico** [comment]
@chathudan Can I ask you to try version `1.1.1`? Is now on Gradle Portal

**Comment by chathudan** [comment]
@colinschoen it's working, thanks for the quick update 

I can see empty header `  @Headers()`  when there no `operationId`.  Can you remove the empty header or add `"X-Operation-ID: loginPost"` using auto-generated operationId

> Empty operationId found for path: get /events/{id}. Renamed to auto-generated operationId: eventsIdGet

**Comment by colinschoen** [comment]
I think this is for @cortinico

**Comment by cortinico** [comment]
> I can see empty header ` @Headers()` when there no `operationId` . Can you remove the empty header ? or add `"X-Operation-ID: eventsIdGet"` using auto-generated operationId

@chathudan Can I ask you to open another issue and explain your scenario please?
