### ISSUE TITLE
Endpoint URL is invalid 

### ISSUE THREAD

**Issue by chathudan** [Yelp/swagger-gradle-codegen#46]
In Retrofit, [baseUrl must end in "/"](https://stackoverflow.com/a/38395703/2380114)  hence endpoint must start without "/" 
Ex: 

Plugin generated endpoint starts with "/" 

 ```kotlin
 @GET("/devices")
  fun devicesGet(
    @retrofit2.http.Query("all") all: Boolean?,
    @retrofit2.http.Query("userId") userId: Int?,
    @retrofit2.http.Query("id") id: Int?,
    @retrofit2.http.Query("uniqueId") uniqueId: String?
  ): Single<List<Device>>
```

which should remove "/" from the API interface like 

```kotlin
  @GET("devices")
  fun devicesGet(
    @retrofit2.http.Query("all") all: Boolean?,
    @retrofit2.http.Query("userId") userId: Int?,
    @retrofit2.http.Query("id") id: Int?,
    @retrofit2.http.Query("uniqueId") uniqueId: String?
  ): Single<List<Device>>
```

**Comment by cortinico** [comment]
Hey @chathudan 

> In Retrofit, baseUrl must end in "/" hence endpoint must start without "/"

The first part of the statement is correct but there is no requirements for endpoints to start with (or without) a slash `/`. Actually trailing slashes have a different semantic on Retrofit, see this answer: https://stackoverflow.com/a/38785498

So I don't think this is a bug, I'm going to close here. Feel free to reopen if you think is the case.
