### ISSUE TITLE
Endpoint URL is invalid

### ISSUE THREAD

**Issue by chathudan** [Yelp/swagger-gradle-codegen#49]
@cortinico This is with regards to #46 , 

My API base URL is something like this  ``` https://example.com/api/v5/```  and Retrofit required "/" at the end of the base URL. 

Since the plugin add "/" to API `@GET("/something")`  so it goes to 
```@GET("/something"): https://example.com/something```

BUT actually, it should go to  ```https://example.com/api/v5/something``` which means the API interface should remove "/"  ```@GET("something")``` . I removed "/" **manually** and the generated SDK working fine. 

How can I resolve this rather modify the generated APIs manually? 

NB: 

> Add trailing slash to base URL, remove leading slash from relative URL.

https://github.com/square/retrofit/issues/907#issuecomment-141834015

**Comment by cortinico** [comment]
Yeah I see your point @chathudan 

Just one question, do you have the `"basePath"` specified in your Swagger file?
Ideally we could remove the trailing slashes for Swagger files that specifies a `basePath`.

**Comment by cortinico** [comment]
A potential fix is in this draft PR #50 
I'd love to get @macisamuele on this discussion as well.

Anyway also the PetStore specs are affected by this bug, so is definitely worth to fix it.

**Comment by chathudan** [comment]
@cortinico sorry for the late reply. It has `basePath`.  My swagger same as the [petstore](https://petstore.swagger.io/v2/swagger.json) does .
