### ISSUE TITLE
Runtime Error on ZonedDateTime

### ISSUE THREAD

**Issue by chathudan** [Yelp/swagger-gradle-codegen#53]
I'm getting runtime error while converting bellow date-time , how can I fix this ? 

```json 
 "expirationTime": {
          "type": "string",
          "format": "date-time",
          "description": "in IS0 8601 format. eg. `1963-11-22T18:30:00Z`"
        }
```

```sh 
Caused by: java.lang.IllegalArgumentException: Cannot serialize abstract class org.threeten.bp.ZoneId
    for class org.threeten.bp.ZoneId zone
    for class org.threeten.bp.ZonedDateTime expirationTime
```

**Comment by cortinico** [comment]
Hey @chathudan 
Are you using the type adapters provided by the generated library?
You need to make sure you provide the `GeneratedConverterFactory` to your Retrofit Builder:

https://github.com/Yelp/swagger-gradle-codegen/blob/08975a09d27988a236a2dc5ce0282aeab7aa3f57/samples/generated-code/src/test/java/com/yelp/codegen/generatecodesamples/InvokeRetrofitTest.kt#L28-L32

**Comment by chathudan** [comment]
@cortinico Thanks, It's my bad, I used `MoshiConverterFactory.create()` instead.
