### ISSUE TITLE
"modelFileFolder" test fails on Windows

### ISSUE THREAD

**Issue by doug-precocity** [Yelp/swagger-gradle-codegen#55]
The "modelFileFolder" test fails when run on a windows machine, due to hardcoded file separator character at this line:

https://github.com/Yelp/swagger-gradle-codegen/blob/bdc9e0f926fdbe57378d00853aa8d6ee390c78f0/plugin/src/test/java/com/yelp/codegen/KotlinGeneratorTest.kt#L156

will submit PR to address this shortly...

**Comment by cortinico** [comment]
Closed by #56
