### ISSUE TITLE
Nullability change in moshi JsonAdapter

### ISSUE THREAD

**Issue by carlosefonseca** [Yelp/swagger-gradle-codegen#74]
I'm getting errors on the generated classes for 
- LocalDateAdapter
- ZonedDateTimeAdapter
- BigDecimalJsonAdapter

The method 
```
override fun toJson(writer: JsonWriter?, value: ZonedDateTime?) {
```
seems to have changed to
```
override fun toJson(writer: JsonWriter, value: ZonedDateTime?) {
```
but I'm using the same moshi versions as the samples (1.8.0)

![Screen Shot 2019-12-13 at 20 09 35](https://user-images.githubusercontent.com/14120/70829076-a5d26700-1de4-11ea-8caf-0dd5d07a393a.png)

**Comment by cortinico** [comment]
Thanks for reporting this @carlosefonseca, and sorry for the late reply.
You're right. We can update the mustache template that generates those `JsonAdapters`.

The fix for this will be in this PR: #78
