### ISSUE TITLE
Why is this one better then the one proposed on swagger codegen github?

### ISSUE THREAD

**Issue by JurajBegovac** [Yelp/swagger-gradle-codegen#8]
Hi, nice idea but I have a question.
Why is this one better than the one mentioned on swagger codegen github? :)

I mean this one:
https://github.com/int128/gradle-swagger-generator-plugin

Thanks and regards

**Comment by cortinico** [comment]
Hey @JurajBegovac 

Thanks for the question.
So the two plugins are pretty similar.

This one contains the Yelp's internal version of the template. 
We designed this plugin to be a more _opinionated_ version of the more general plugins you can find online. Most of them contains several templates that are generally not up to date, and you need to spend time to adapt them and maintain them.

Our template uses a combination of Kotlin, Retrofit, RxJava2, Moshi, ThreeTenAbp and we thought it was valuable to share it with the open source community :)

Does this answer your question?

**Comment by JurajBegovac** [comment]
Hi,

I appreciate that you shared it with the community but just wondered if you could just enhance the existing one.
Because that one already supports Kotlin and Retrofit (I'm not sure about the other libraries you mentioned).

But nvm, I assume it was easier to create your own :)

And thanks for the answer

**Comment by cortinico** [comment]
> But nvm, I assume it was easier to create your own :)

Yeah basically that's the point.
Templates tends to be harder to maintain, so that's the reason why we decided to have our own project.
