### ISSUE TITLE
Generate files under  `build/generated/`

### ISSUE THREAD

**Issue by martinbonnin** [Yelp/swagger-gradle-codegen#98]
The plugin could generate the files under a separate `build/generated` directory so as not to pollute the `src/main/java` sourceSet. Also, it would be nice to add `generateSwagger` as a prerequisite of `compileKotlin`

**Comment by cortinico** [comment]
> The plugin could generate the files under a separate build/generated directory so as not to pollute the src/main/java sourceSet

Yup, that's definitely an improvement we can do: changing the default `outputDir` to a directory inside `build`.

> Also, it would be nice to add generateSwagger as a prerequisite of compileKotlin

I'm against this point honestly. The idea behind the plugin is that it should only offer a task to generate the code. Is up to the developer to decide whether to compile also the code or not.

**Comment by martinbonnin** [comment]
> The idea behind the plugin is that it should only offer a task to generate the code. Is up to the developer to decide whether to compile also the code or not.

Yea, adding all this plumbing can become quite cumbersome.

**Comment by cortinico** [comment]
I just realised that the default `outputDir` is actually:

```kotlin
const val DEFAULT_OUTPUT_DIR = "/gen"
...
val defaultOutputDir = File(project.buildDir, DEFAULT_OUTPUT_DIR)
```

So I guess we're good to close this issue.
